document.getElementById("nombre").innerHTML+=`Carlos Perez`;
document.getElementById("dni").innerHTML+=`41459399`;
document.getElementById("intereses").innerHTML=`Gastronomia`;
document.getElementById("nacimiento").innerHTML+=`24/02/2000`;
document.getElementById("sexo").innerHTML+=`Hombre`;
document.getElementById("escuela").innerHTML+=`San Belgrano N10`
document.getElementById("domicilio").innerHTML+=`Martinez 2100`;
document.getElementById("ciudad").innerHTML+=`Villa Urquiza`;
document.getElementById("provincia").innerHTML+=`CABA`;
document.getElementById("celular").innerHTML+=`CABA`;
document.getElementById("instagram").innerHTML+=`CarLopez`;
document.getElementById("twitter").innerHTML+=`CarlosPerez`;
document.getElementById("linkedin").innerHTML+=`CarlosPerez`;
document.getElementById("practica").innerHTML+=`Administracion - Administracion de Pyme`;
document.getElementById("deskPractica").innerHTML+=`Se le impartieron conocimientos que lo inmergen en la administracion de mercados emergentes`;
document.getElementById("ultimaConexion").innerHTML+=`Hace 2 dias..`;
